### PR TITLE
Add Set Icon and Username ability; add missing onQueue declaration

### PR DESCRIPTION
**Pull request by d2inco**
I have the need to set the slack Display Name, and icon next to it, when my application posts into my alert channel; this code adds it, and updates the README for it.

It also adds a missing declaration for `onQueue` which was causing my IDE to not know that it was there.

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add tests for this one at well?

**Comment by d2inco** [comment]
@freekmurze fixed an icon_url reference and added tests.   I cannot figure out how to run tests against the items in vendor/tests, so am unable to verify them.   But if they run for you, we should be good.   I have the current changes working in my dev environment here.

**Comment by freekmurze** [comment]
Thanks!

**Comment by d2inco** [comment]
> Thanks!

Awesome, thank you!

**Comment by d2inco** [comment]
> Thanks!

Awesome, thank you!

**Pull request merged**
